version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: DockerFile
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/ticketdb
    volumes:
      - .:/usr/src/app
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ticketdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres_data:
